# Generated by Django 4.2.2 on 2023-09-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_imagedetection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetection',
            name='image',
            field=models.TextField(max_length=255),
        ),
    ]
